### PR TITLE
Export NoopTracer

### PR DESCRIPTION
**Pull request by danilobuerger**
I would like to use this to opt out of tracing under certain conditions.

### CODE REVIEW

**Comment by Flarna** [comment]
Could you provide some more details here?
Usually samplers are the entities to decide if an exported span should be created or not.

To completely opt out from tracing the easiest way is to just not call `setTracerProvider`.

**Comment by danilobuerger** [comment]
It would make it inline with other language sdks, for example go exposes it: https://pkg.go.dev/go.opentelemetry.io/otel/trace#NewNoopTracerProvider

**Comment by Flarna** [comment]
@danilobuerger That doesn't answer my questions. One could argue it should be removed there :o)

**Comment by danilobuerger** [comment]
Thats fine. Not here to argue.

**Comment by Flarna** [comment]
The main reason for not exporting is to reduce the amount of APIs to maintain and to avoid wrong/misuse. A similar API cleanup was done for metrics to prepare it for GA.

Therefore I asked for the use case. If it is a valid use case which can't be archived with current API exposing the Noop classes/instances might be good. Or to add another API to fulfill your usecase.

But I see no reason to expose them just to have them exposed.

**Comment by danilobuerger** [comment]
For my use case I already applied this PR with patch-package so its already working for me and I am using the `NoopTracer`. I just thought I would surface this upstream here. If it's not wanted, thats fine.

**Comment by dyladan** [comment]
Moving discussion of this request to https://github.com/open-telemetry/opentelemetry-js/issues/3315 as this repo is being archived.

**Pull request closed without merging**
