### PR TITLE
docs(api): update earliest supported node version

### PR DESCRIPTION
**Pull request by svetlanabrennan**
Signed-off-by: Svetlana Brennan <svetlana.svn@gmail.com>

Partially fixes Issue #[2721](https://github.com/open-telemetry/opentelemetry-js/issues/2721)

- See checklist item 1 mentioned [here](https://github.com/open-telemetry/opentelemetry-js/issues/2721#issuecomment-1076570990)

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Review by legendecas — APPROVED** [review]

**Review by vmarchaud — COMMENTED** [review]
can we change this on the API without a major bump ?

EDIT: I understand that the SDK requires 8.12 for correct timestamp but the api do not right ?

**Comment by Flarna** [comment]
I did a quick look and it seems API is not using `perf_hooks` so it will even work with node.js 8.0.0.

**Comment by vmarchaud** [comment]
> I did a quick look and it seems API is not using perf_hooks so it will even work with node.js 8.0.0.

API should be platform agnostic anyway so we should keep the support i think

**Comment by Rauno56** [comment]
> I did a quick look and it seems API is not using `perf_hooks` so it will even work with node.js 8.0.0.

That's right. @svetlanabrennan, perhaps we can close this PR then as technically API is not restricted.

**Pull request closed without merging**
